# Generated by Django 3.1.6 on 2021-03-02 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_auto_20210212_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentClientReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('responsible_person', models.CharField(max_length=50)),
                ('phone_number1', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998991234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number2', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998991234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('image', models.ImageField(upload_to='client')),
                ('assumption_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sale_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
