# Generated by Django 3.1.6 on 2021-03-02 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_agentclientreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentclientreport',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998991234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
