# Generated by Django 3.1.6 on 2021-02-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_discount', '0003_auto_20210220_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
