# Generated by Django 3.1.6 on 2021-02-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('limited', 'limited'), ('unlimited', 'unlimited')], max_length=10)),
                ('category', models.CharField(choices=[('sausages', 'sausages'), ('chickens', 'chicken products'), ('dairy', 'dairy'), ('others', 'others')], max_length=10)),
            ],
        ),
    ]
