# Generated by Django 3.1.6 on 2021-02-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210216_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
    ]
