# Generated by Django 3.1.6 on 2021-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
