# Generated by Django 3.1.6 on 2021-02-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_buyorder_provider'),
        ('report', '0002_auto_20210227_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='sell_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.sellorder'),
            preserve_default=False,
        ),
    ]
