# Generated by Django 3.1.6 on 2021-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_profit_sell_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
