# Generated by Django 3.1.6 on 2021-03-03 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210303_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleagentreport',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
