# Generated by Django 3.1.6 on 2021-03-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20210303_1722'),
        ('report', '0005_saleagentreport_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='sell_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.sellorder'),
        ),
    ]
