# Generated by Django 3.1.6 on 2021-02-06 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998991234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('responsible_agent', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
