# Generated by Django 3.1.6 on 2021-03-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20210308_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='longitude',
        ),
    ]
