# Generated by Django 3.1.6 on 2021-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEO_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('director_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commodity_accountant_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('accountant_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cashier_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('agent_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('agent_flexible_salary', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
