# Generated by Django 3.1.6 on 2021-02-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20210224_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedsalary',
            name='flexible',
            field=models.BooleanField(default=False),
        ),
    ]
