# Generated by Django 3.1.6 on 2021-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20210224_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
