# Generated by Django 3.1.6 on 2021-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
