# Generated by Django 3.1.6 on 2021-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20210217_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planitem',
            name='sold_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
