# Generated by Django 3.1.6 on 2021-02-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20210218_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitem',
            name='sold_quantity',
        ),
    ]
