# Generated by Django 3.1.6 on 2021-02-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210210_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellorder',
            name='sale_agent',
        ),
    ]
