# Generated by Django 3.1.6 on 2021-02-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_saleagentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('credit_card', 'credit_card'), ('debt', 'debt')], max_length=15)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.buyorder')),
            ],
        ),
    ]
