# Generated by Django 3.1.6 on 2021-02-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_buyorderpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='payment_type',
        ),
    ]
