# Generated by Django 3.1.6 on 2021-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210213_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
