# Generated by Django 3.1.6 on 2021-02-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210213_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
