# Generated by Django 3.1.6 on 2021-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210213_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
