# Generated by Django 3.1.6 on 2021-02-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210215_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedclientproduct',
            old_name='returned_products_quantity',
            new_name='returned_quantity',
        ),
        migrations.RenameField(
            model_name='failedproviderproduct',
            old_name='returned_products_quantity',
            new_name='returned_quantity',
        ),
    ]
