# Generated by Django 3.1.6 on 2021-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_buyorder_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedclientproduct',
            name='failed_status',
            field=models.CharField(choices=[('valid', 'valid'), ('invalid', 'invalid')], max_length=8),
        ),
        migrations.AlterField(
            model_name='failedproviderproduct',
            name='failed_status',
            field=models.CharField(choices=[('valid', 'valid'), ('invalid', 'invalid')], max_length=8),
        ),
    ]
