# Generated by Django 3.1.6 on 2021-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20210303_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderpayment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('credit_card', 'credit_card'), ('money_transfer', 'money_transfer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sellorderpayment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('credit_card', 'credit_card'), ('money_transfer', 'money_transfer')], max_length=15),
        ),
    ]
